name: weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio:
  dio_http_cache:
  auto_size_text:
  flutter_spinkit:
  form_field_validator:
  get_storage:
  intl:
  google_fonts:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter





flutter: 
  uses-material-design: true

  assets:
    - assets/images/